In [1]:
import scipy.stats as scipyStats
import numpy as np
import math

In [18]:
#hypergeo
N = 19
x = 1
k = 9
n = 3

# p(k, M, n, N) == p(x, N, k, n)

total = 0
part = -scipyStats.hypergeom.cdf(x, N, k, n) * 100

print((total - part) / 100)

0.541795665634675


In [6]:
# bin
x = 0
n = 13
p = 0.10

total = 100
part = scipyStats.binom.cdf(x, n, p) * 100

print((total - part) / 100)

0.7458134171671


In [9]:
# poisson

x = 4
mu = 4

total = 100

part = scipyStats.poisson.cdf(x, mu) * 100

print((total - part) / 100)

0.3711630648201266


In [97]:
i = 123
print(len(str(i)))

3


In [46]:
# interval estimation of
# population mean

sample_mean = 5.6
n = 650
sigma = 1.3
confidence = 0.98
alpha = 1 - confidence
alpha_2 = round(alpha / 2, 4)
print(alpha_2)
z_score = abs(round(scipyStats.norm.ppf(0.10, 0, 1), 2))
error = z_score * (sigma/math.sqrt(n))
L = sample_mean - error
R = sample_mean + error

# intervals = [math.floor(L) , math.ceil(R)]
intervals = [L, R]

for i in range(0, len(intervals)):
    intervals[i] = round(intervals[i], 1)

print(intervals)
print(error)


0.01
[5.5, 5.7]
0.06526744977398764


In [50]:
# need size of n required for error

# sigma = 0.3

confidence = 0.95
error = 0.25

alpha = 1 - confidence
alpha_2 = alpha / 2
print('alpha/2: ', round(alpha_2, 2))

z_score = abs(round(scipyStats.norm.ppf(alpha_2, 0, 1), 2))
print('z score: ', z_score)

n = math.ceil(math.pow(z_score * (sigma/error), 2))

print('suggested n: ', n)


alpha/2:  0.03
z score:  1.96
suggested n:  139


In [34]:
# t distribution 
# confidence interval
# n < 30 and rv is uniform

numbers = [6,16,19,12,15,14]
numbers = np.array(numbers)
n = numbers.size
degrees_of_freedom = n - 1
confidence = 0.90

sample_mean = numbers.mean()
print('sample_mean: ', round(sample_mean, 2))

numerator = lambda a, b: (a - b)**2
sum = 0
for number in numbers:
    sum = sum + numerator(number, sample_mean)

sample_variance = sum / (n - 1)
print('sample variance: ', round(sample_variance, 2))
sample_sigma = math.sqrt(sample_variance)
print('sample sigma: ', sample_sigma)
sigma = sample_sigma / math.sqrt(n)
print('sigma: ', round(sigma, 2))

#---------------------

# n = 14
# degrees_of_freedom = n - 1
# confidence = 0.98

# sample_mean = 0.360
# sample_sigma = 0.0061
# numerator = lambda x, y: (x - y)**2

# sigma = sample_sigma / math.sqrt(n)

#-----------------------

alpha = 1 - confidence
alpha_half = alpha / 2
print('alpha_half: ', round(alpha_half, 2))
t_value = abs(round(scipyStats.t.ppf(alpha_half, degrees_of_freedom), 4))
print('t-value: ', round(t_value, 2))
error = t_value * sigma
print('error: ', round(error, 2))
L = sample_mean - error
R = sample_mean + error
interval = [round(L, 2), round(R, 2)]
print(interval)


sample_mean:  13.67
sample variance:  19.47
sample sigma:  4.412104562073146
sigma:  1.8
alpha_half:  0.05
t-value:  2.02
error:  3.63
[10.04, 17.3]


In [32]:
# normal
#     z > x1 and z < x2

# loc == mean
# scale == std
x1 = -0.78
mean1 = 0
std1 = 1

prob1 = 1 - scipyStats.norm.cdf(x1, mean1, std1)

x2 = -0.88
mean2 = 0
std2 = 1

prob2 = scipyStats.norm.cdf(x2, mean2, std2)

ans = round(prob2 + prob1, 4)
print(ans)

0.9717


In [87]:
# normal
#  z > x

# loc == mean
# scale == std
# n = 228
# p = 0.18
# sigma = math.sqrt((p*(1 - p))/n)
# x = (0.14 - p) / sigma

n = 53
sigma = 10 / math.sqrt(n)
x = (163.7 - 161) / sigma

mean = 0
std = 1

prob = 1 - scipyStats.norm.cdf(x, mean, std)

print(round(prob, 4))

0.0247


In [85]:
# normal
#  z < x

# loc == mean
# scale == std
# n = 577
# p = 0.06
# sigma = math.sqrt((p*(1 - p))/n)

n = 53
sigma = 10 / math.sqrt(n)
x = (38 - 16_445) / sigma
mean = 0
std = 1

prob = scipyStats.norm.cdf(x, mean, std)

print(round(prob, 4))

0.7483


In [86]:
# normal
#     x1 <  z < x2

# loc == mean
# scale == std
# n = 305
# p = 0.06
# sigma = math.sqrt((p*(1 - p))/n)

n = 53
dev = 10
sigma = dev / math.sqrt(n)
x1 = (-38) / sigma
mean = 0
std = 1

prob1 = scipyStats.norm.cdf(x1, mean, std)

x2 = (38) / sigma

prob2 = scipyStats.norm.cdf(x2, mean, std)

ans = round(prob2 - prob1, 4)
print(round(ans, 4))

0.8326


In [115]:
# MAD mean absolute difference

x = [4,10,9,11,9,7, 200]
x = np.array(x)
mean = x.mean()
numerator = lambda a, b : abs(a - b)
sum = 0
for number in x:
    sum = sum + numerator(number, mean)

print(sum/len(x))

46.93877551020408


In [7]:
# variance population sigma

x = [4,4,13,10,9,11,5,13,2,10,7,2]
x = np.array(x)
mean = x.mean()
print('mean: ', mean)
numerator = lambda a, b : abs(a - b)**2
sum = 0
for number in x:
    sum = sum + numerator(number, mean)

def mode(x):
    occur = {}
    highest_count = 1
    for number in x:
        if occur.get(number) == None:
            occur[number] = 1
        else:
            occur[number] = occur[number] + 1
            if highest_count < occur[number]:
                highest_count = occur[number]
    
    if highest_count == 1:
        return []

    keys = occur.keys()
    modes = []
    for key in keys:
        if occur[key] == highest_count:
            modes.append(key)

    return modes

modes = mode(x)

print('mode: ', modes)

s_2 = sum/(x.size)
print('variance: ', s_2)

s = math.sqrt(s_2)
print('standard deviation: ', s)

x.sort()
print(x)
range = x[x.size - 1] - x[0]
print('range:', range) 

def percentile(x, percent):
    L = 0
    R = x.size
    if percent == 0.0:
        return x[0]
    elif percent == 0.25:
        R = math.floor(x.size / 2)
    elif percent == 0.75:
        L = math.floor(x.size / 2)
    elif percent == 1.0:
        return x[x.size - 1]

    mid = math.floor(L + ((R - L) / 2))

    if (R - L) % 2 != 0:
        return x[mid] 
    else:
        return (x[mid] + x[mid-1]) / 2

print('0 percentile:', percentile(x, 0.0))
print('25 percentile: ', percentile(x, 0.25))
print('50 percentile: ', percentile(x, 0.50))
print('75 percentile: ', percentile(x, 0.75))
print('100 percentile: ', percentile(x, 1.0))

mean:  7.5
mode:  [4, 13, 10, 2]
variance:  14.916666666666666
standard deviation:  3.8622100754188224
[ 2  2  4  4  5  7  9 10 10 11 13 13]
range: 11
0 percentile: 2
25 percentile:  4.0
50 percentile:  8.0
75 percentile:  10.5
100 percentile:  13


In [34]:
# variance sample s

x = [0.548,0.660,0.675,0.543,0.644,0.551,0.661,0.549,0.619,0.533,0.563,0.560,0.534,0.669,0.549,0.551,0.593,0.593,0.674,0.526]
x = np.array(x)
mean = x.mean()
print('mean: ', mean)
numerator = lambda a, b : abs(a - b)**2
sum = 0
for number in x:
    sum = sum + numerator(number, mean)

s_2 = sum/(x.size-1)
print('variance: ', s_2)

s = math.sqrt(s_2)
print('standard deviation: ', s)

x.sort()
print(x)
range = x[x.size - 1] - x[0]
print('range:', range) 

median = -1
if x.size % 2 != 0:
    index = x.size/2
    median = math.floor(index)
else:
    index1 = math.floor(x.size/2)
    index2 = math.floor(index1 - 1)
    median = (x[index1] + x[index2]) / 2

print('median', median)

def percentile(x, percent):
    L = 0
    R = x.size - 1
    if percent == 0.25:
        R = math.floor(x.size / 2)
    elif percent == 0.75:
        L = math.floor(x.size / 2)

    mid = math.floor(L + ((R - L) / 2))

    if R - L % 2 != 0:
        return x[mid]    
    else:
        return (x[mid] + x[mid-1]) / 2
    
print('25 percentile: ', percentile(x, 0.25))
print('50 percentile: ', percentile(x, 0.50))
print('75 percentile: ', percentile(x, 0.75))


mean:  0.58975
variance:  0.0029854605263157897
standard deviation:  0.05463936791651043
[0.526 0.533 0.534 0.543 0.548 0.549 0.549 0.551 0.551 0.56  0.563 0.593
 0.593 0.619 0.644 0.66  0.661 0.669 0.674 0.675]
range: 0.14900000000000002
median 0.5615
25 percentile:  0.549
50 percentile:  0.56
75 percentile:  0.644


In [13]:

# variance population sigma
# for specifically 

classes = [[61,66],[67, 72],[73, 78],[79, 84],[85,90]]
frequency = [14, 5, 5, 5, 13]

classes = np.array(classes)
frequency = np.array(frequency)

mean_classes = []

for some_class in classes:
    mean_classes.append(some_class.mean())

mean_classes = np.array(mean_classes)

print(mean_classes)

print('mean classes: ', mean_classes)

sum_frequency = frequency.sum()
mean_dataset = mean_classes.dot(frequency) / sum_frequency

print('mean dataset: :', mean_dataset)

def mode(freq, b):

    max_frequency = freq.max()
    if max_frequency == 1:
        return []
    modes = []

    b_size = b.shape

    i = 0
    while(i < b_size[0]):
        if freq[i] == max_frequency:
            modes.append(b[i])
        i = i + 1
    
    #     if frequency[i] == max_frequency:
    #         modes.append()

    return modes

modes = mode(frequency, classes)

print('mode: ', modes)

sum = 0

numerator = lambda a,b,c : (a - b)**2 * c

for i,j in zip(mean_classes, frequency):
    sum = sum + numerator(i, mean_dataset, j)

s_2 = sum/(mean_classes.size)
print('variance: ', s_2)

s = math.sqrt(s_2)
print('standard deviation: ', s)

class_size = classes.shape

range = classes[class_size[0]-1][class_size[1]-1] - classes[0][0] 
print('range: ', range)

[63.5 69.5 75.5 81.5 87.5]
mean classes:  [63.5 69.5 75.5 81.5 87.5]
mean dataset: : 75.21428571428571
mode:  [array([61, 66])]
variance:  848.9142857142857
standard deviation:  29.13613367820593
range:  29


In [90]:
classes = [[61,66],[67, 72],[73, 78],[79, 84],[85,90]]
frequency = [14, 5, 5, 5, 13]

classes = np.array(classes)
frequency = np.array(frequency)

mean_classes = []

for some_class in classes:
    mean_classes.append(some_class.mean())

mean_classes = np.array(mean_classes)

print(mean_classes)

print('mean classes: ', mean_classes)

sum_frequency = frequency.sum()
mean_dataset = mean_classes.dot(frequency) / sum_frequency

print('mean dataset: :', mean_dataset)

def mode(freq, b):

    max_frequency = freq.max()
    if max_frequency == 1:
        return []
    modes = []

    b_size = b.shape

    i = 0
    while(i < b_size[0]):
        if freq[i] == max_frequency:
            modes.append(b[i])
        i = i + 1
    
    #     if frequency[i] == max_frequency:
    #         modes.append()

    return modes

modes = mode(frequency, classes)

print('mode: ', modes)

sum = 0

numerator = lambda a,b,c : (a - b)**2 * c

for i,j in zip(mean_classes, frequency):
    sum = sum + numerator(i, mean_dataset, j)

s_2 = sum/(mean_classes.size)
print('variance: ', s_2)

s = math.sqrt(s_2)
print('standard deviation: ', s)

class_size = classes.shape

range = classes[class_size[0]-1][class_size[1]-1] - classes[0][0] 
print('range: ', range)

[63.5 69.5 75.5 81.5 87.5]
mean classes:  [63.5 69.5 75.5 81.5 87.5]
mean dataset: : 75.21428571428571
mode:  [array([61, 66])]
variance:  848.9142857142857
standard deviation:  29.13613367820593
range:  29


In [91]:


x = [3, 4, 5, 6, 7, 8]
probs = [0.1, 0.1, 0.3, 0.2, 0.1, 0.2]

x = np.array(x)
probs = np.array(probs)

x_2 = x * x

var = x_2.dot(probs) - (x.dot(probs)**2)
print(var)
# print(math.sqrt(var))

2.4099999999999966


In [92]:
x1 = [-5000, 50000, 80000]
probs1 = [0.63, 0.09, 0.28]

x1 = np.array(x1)
probs1 = np.array(probs1)
x_2_1 = x1 * x1

# print(x1.dot(probs1))

x2 = [-25000, 35000, 40000]
probs2 = [0.35, 0.41, 0.24]

x2 = np.array(x2)
probs2 = np.array(probs2)
x_2_2 = x2 * x2

# print(x2.dot(probs2))
var1 = x_2_1.dot(probs1) - (x1.dot(probs1)**2)
var2 = x_2_2.dot(probs2) - (x2.dot(probs2)**2)
print(var1)
print(var2)

1468687500.0
873960000.0


In [93]:
def f(x):
    return 81 * x

def countNumbersBetween(startDigit, endDigit):
    count = 1
    number = f(count)
    start_number = number
    last_number = number

    while len(str(start_number)) < startDigit:
        count = count + 1
        start_number = f(count)

    last_number = start_number

    while len(str(last_number)) < endDigit:
        count = count + 1
        last_number = f(count)

    return last_number - start_number

# Numbers Between Additional Digit
# from 2 digits to 5
#      2d, 3d, 4d, 5d
# index 0, 1, 2, 3
sizeDiffDist = {}
for i in range(2, 11):
    sizeDiffDist[countNumbersBetween(i, i+1)] = [i, i+1]

# sizeDiffBetweenDigitCount = np.array()

print(sizeDiffDist)

TypeError: 'numpy.int64' object is not callable

In [ ]:
def f(x):
    return 81 * x

def countNumbersBetween(startDigit, endDigit):
    count = 1
    number = f(count)
    start_number = ((math.pow(10, startDigit - 1) // f(1)) + 1) * f(1)
    last_number = ((math.pow(10, endDigit - 1) // f(1)) + 1) * f(1)
    return last_number - start_number

# Numbers Between Additional Digit
# from 2 digits to 5
#      2d, 3d, 4d, 5d
# index 0, 1, 2, 3
sizeDiffDist = {}
for i in range(2, 20):
    sizeDiffDist[countNumbersBetween(i, i+1)] = [i, i+1]

# sizeDiffBetweenDigitCount = np.array()

print(sizeDiffDist)

{81.0: [2, 3], 891.0: [3, 4], 8991.0: [4, 5], 89991.0: [5, 6], 899991.0: [6, 7], 8999991.0: [7, 8], 89999991.0: [8, 9], 900000072.0: [9, 10], 8999999991.0: [10, 11], 89999999991.0: [11, 12], 899999999991.0: [12, 13], 8999999999991.0: [13, 14], 89999999999991.0: [14, 15], 899999999999991.0: [15, 16], 8999999999999990.0: [16, 17], 8.999999999999998e+16: [17, 18], 9.000000000000001e+17: [18, 19], 9e+18: [19, 20]}


In [ ]:
x = [8,9,10,5,3,7]
x = np.array(x)
x.sort()
print(x)
print(x.mean())

[ 3  5  7  8  9 10]
7.0
